FROM ghcr.io/cross-rs/riscv64gc-unknown-linux-gnu@sha256:d1f4b2e75b1a75d49c1bafc342832c81bb66a801ae00b77302916c8d4a869686
RUN dpkg --add-architecture riscv64 && \
    printf '%s\n' \
        'Types: deb' \
        'URIs: https://ports.ubuntu.com/ubuntu-ports' \
        'Suites: noble noble-updates noble-backports noble-security' \
        'Components: main restricted universe multiverse' \
        'Architectures: riscv64' \
        'Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg' \
        > /etc/apt/sources.list.d/riscv64.sources && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        pkg-config \
        libwayland-dev:riscv64 \
        libxkbcommon-dev:riscv64 && \
    rm -rf /var/lib/apt/lists/*
