FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu@sha256:e3f7d4ee29f4198c22f84a8d05ab52ec209e7900bd394888b40ea81ca364ec6c
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends pkg-config libwayland-dev libxkbcommon-dev && rm -rf /var/lib/apt/lists/*
