#!/usr/bin/env python3
"""Generate localized desktop and AppStream fields."""

from __future__ import annotations

import re
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
I18N = ROOT / "i18n"
DESKTOP = ROOT / "resources/org.cosmic_utils.compass.desktop"
METAINFO = ROOT / "resources/org.cosmic_utils.compass.metainfo.xml"
PREVIEW_README = ROOT / "preview/README.md"
FTL = "compass.ftl"
SOURCE = "en"
NL = chr(10)


def translations() -> dict[str, dict[str, str]]:
    values: dict[str, dict[str, str]] = {}
    for path in sorted(I18N.glob(f"*/{FTL}")):
        for line in path.read_text(encoding="utf-8").splitlines():
            match = re.match(r"^([a-z0-9-]+) = (.*)$", line)
            if match:
                values.setdefault(match.group(1), {})[path.parent.name] = match.group(2)
    return values


def desktop_text(values: dict[str, dict[str, str]]) -> str:
    mapping = {
        "Name": "compass",
        "Comment": "desktop-comment",
        "Keywords": "desktop-keywords",
    }
    source = [
        line
        for line in DESKTOP.read_text(encoding="utf-8").splitlines()
        if not re.match(r"^[A-Za-z]+\[[^]]+\]=", line)
    ]
    output: list[str] = []
    for line in source:
        field = line.partition("=")[0]
        key = mapping.get(field)
        if key is None:
            output.append(line)
            continue
        output.append(f"{field}={values[key][SOURCE]}")
        for language, value in sorted(values[key].items()):
            if language != SOURCE:
                output.append(f"{field}[{language.replace('-', '_')}]={value}")
    return NL.join(output) + NL


def element_group(tag: str, values: dict[str, str], indent: str) -> str:
    lines = [f"{indent}<{tag}>{escape(values[SOURCE])}</{tag}>"]
    lines.extend(
        f'{indent}<{tag} xml:lang="{language}">{escape(value)}</{tag}>'
        for language, value in sorted(values.items())
        if language != SOURCE
    )
    return NL.join(lines)


def replace_group(text: str, tag: str, values: dict[str, str]) -> str:
    pattern = re.compile(
        rf"^(\s*)<{tag}(?![^>]*xml:lang)[^>]*>.*?</{tag}>"
        rf"(?:\n\s*<{tag} xml:lang=.*?</{tag}>)*",
        re.MULTILINE,
    )
    match = pattern.search(text)
    if not match:
        raise SystemExit(f"missing <{tag}> in {METAINFO.name}")
    replacement = element_group(tag, values, match.group(1))
    return text[: match.start()] + replacement + text[match.end() :]


def replace_groups(text: str, tag: str, groups: list[dict[str, str]]) -> str:
    """Replace successive unlocalized elements and their translated siblings."""
    pattern = re.compile(
        rf"^(\s*)<{tag}(?![^>]*xml:lang)[^>]*>.*?</{tag}>"
        rf"(?:\n\s*<{tag} xml:lang=.*?</{tag}>)*",
        re.MULTILINE,
    )
    matches = list(pattern.finditer(text))
    if len(matches) != len(groups):
        raise SystemExit(
            f"expected {len(groups)} <{tag}> elements, found {len(matches)} in {METAINFO.name}"
        )
    for match, values in reversed(list(zip(matches, groups))):
        replacement = element_group(tag, values, match.group(1))
        text = text[: match.start()] + replacement + text[match.end() :]
    return text


def preview_readme(values: dict[str, dict[str, str]]) -> str:
    captions = [
        values["metainfo-caption-desktop"][SOURCE],
        values["metainfo-caption-phone"][SOURCE],
    ]
    cells = [
        f"![{caption}](preview-{index:03}.png)<br>**{caption}**"
        for index, caption in enumerate(captions, 1)
    ]
    rows = [cells[index : index + 2] for index in range(0, len(cells), 2)]
    lines = [
        "<!-- Generated by scripts/gen-metadata.py. Edit captions in i18n/en/compass.ftl and run `just generate`. -->",
        "",
        "# Compass screenshots",
        "",
        f"*{values['metainfo-summary'][SOURCE]}.*",
        "",
        "|  |  |",
        "| :---: | :---: |",
    ]
    lines.extend(f"| {' | '.join(row + [''] * (2 - len(row)))} |" for row in rows)
    lines.extend(["", "## Appearance variants", ""])
    for index, caption in enumerate(captions, 1):
        light = f"variants/preview-{index:03}-light.png"
        if (ROOT / "preview" / light).exists():
            lines.extend([
                f"### {caption}",
                "",
                "| Dark | Light |",
                "| :---: | :---: |",
                f"| ![{caption}, dark](preview-{index:03}.png) | ![{caption}, light]({light}) |",
                "",
            ])
    lines.extend([
        "---",
        "",
        "Regenerate them with `just generate-previews`. The digest-pinned container",
        "verifies its package lock, then uses fixed demo headings and software",
        "rendering so captures are reproducible.",
        "Refresh that lock intentionally with `just update-preview-environment`.",
        "",
        "[Back to the project README](../README.md)",
        "",
    ])
    return NL.join(lines)


def main() -> None:
    values = translations()
    required = [
        "compass",
        "desktop-comment",
        "desktop-keywords",
        "metainfo-summary",
        "metainfo-description",
        "metainfo-caption-desktop",
        "metainfo-caption-phone",
    ]
    missing = [key for key in required if SOURCE not in values.get(key, {})]
    if missing:
        raise SystemExit(f"missing English Fluent keys: {', '.join(missing)}")
    DESKTOP.write_text(desktop_text(values), encoding="utf-8")
    text = METAINFO.read_text(encoding="utf-8")
    for tag, key in [
        ("name", "compass"),
        ("summary", "metainfo-summary"),
        ("p", "metainfo-description"),
    ]:
        text = replace_group(text, tag, values[key])
    caption_keys = [
        "metainfo-caption-desktop",
        "metainfo-caption-phone",
    ]
    text = replace_groups(text, "caption", [values[key] for key in caption_keys])
    METAINFO.write_text(text, encoding="utf-8")
    PREVIEW_README.parent.mkdir(parents=True, exist_ok=True)
    PREVIEW_README.write_text(preview_readme(values), encoding="utf-8")
    print("generated localized desktop and AppStream metadata")


if __name__ == "__main__":
    main()
